name: dwellir-harvester
base: core24
version: 0.1.0
summary: Collect node metadata
description: |
  Runs a configurable collectors that serves the results as JSON.
  Configure via `snap set`.

grade: devel
confinement: strict

# This connects the dummychain snap to the dwellir-harvester snap  
plugs:
  dummychain-bins:
    interface: content
    content: executables
    target: $SNAP/usr/local
# This connects the reth snap to the dwellir-harvester snap  
  reth-bins:
    interface: content
    content: executables
    target: $SNAP/usr/local
# This connects the polkadot snap to the dwellir-harvester snap  
  polkadot-bins:
    interface: content
    content: executables
    target: $SNAP/usr/local


# Our apps that uses snaps needs
# plugs to be  able to call the binaries.
# This is a security feature of snaps.
# The dwellir-harvester hence needs plugs for snaps collectors.
apps:
  dwellir-harvester:
    command: bin/python3 -m dwellir_harvester.cli
    environment:
      PATH: "$SNAP/venv/bin:$PATH"
    plugs: 
      - network
      - dummychain-bins
      - polkadot-bins
      - reth-bins

  metadata-daemon:
    command: bin/python3 -m dwellir_harvester.daemon
    daemon: simple
    restart-condition: always
    environment:
      PATH: "$SNAP/venv/bin:$PATH"
    plugs: 
      - network
      - network-bind
      - dummychain-bins
      - polkadot-bins
      - reth-bins
      - home


parts:
  app:
    plugin: python
    source: .
    # If you need extra pip deps beyond your package, list them here:
    python-packages: []
    # (optional) If your build needs system headers/tools, list them here:
    build-packages: []
    # No stage-packages needed; the plugin vendors a self-contained runtime.


  hooks:
    plugin: dump
    source: snap
    organize:
      hooks/configure: hooks/configure
