name: blockchain-collector
base: core24
version: 0.1.0
summary: Collect blockchain node metadata and expose it over HTTP
description: |
  Runs a configurable collector (e.g., reth) and serves the resulting JSON file
  from $SNAP_COMMON/metadata.json at /metadata. Configure via `snap set`.

grade: devel
confinement: strict

# This connects the dummychain snap to the blockchain-collector snap  
plugs:
  dummychain-bins:
    interface: content
    content: executables
    target: $SNAP/usr/local


# Our apps that uses snaps needs
# plugs to be  able to call the binaries.
# This is a security feature of snaps.
# The blockchain-collector hence needs plugs for snaps collectors.
apps:
  blockchain-collector:
    command: bin/python3 -m blockchain_collector.cli
    environment:
      PATH: "$SNAP/venv/bin:$PATH"
    plugs: [network, dummychain-bins]

  metadata-daemon:
    command: bin/python3 -m blockchain_collector.daemon
    daemon: simple
    restart-condition: always
    environment:
      PATH: "$SNAP/venv/bin:$PATH"
    plugs: [network, network-bind, dummychain-bins]


parts:
  app:
    plugin: python
    source: .
    # If you need extra pip deps beyond your package, list them here:
    python-packages: []
    # (optional) If your build needs system headers/tools, list them here:
    build-packages: []
    # No stage-packages needed; the plugin vendors a self-contained runtime.


  hooks:
    plugin: dump
    source: snap
    organize:
      hooks/configure: hooks/configure
